name: My Action

on:
  pull_request:
    

jobs:
  call-workflow-label-1:
    name: Checking Labels
    if: contains( github.event.pull_request.labels.*.name, 'Label1')
    uses: ./.github/workflows/wf_label1.yml
      
